function generate_locomotor_race

info_needed = struct('Framerate',15,...
                     'Duration',3,...
                     'Coordinates','minperturbation_coords',...
                     'sysplotterpath', '/Users/rlhatton/GeometricSystemPlotter/ProgramFiles',...
                     'datapath', '/Users/rlhatton/GeometricSystemPlotter/UserFiles/GenericUser/sysplotter_data/',...
                     'UserFile_path', '/Users/rlhatton/GeometricSystemPlotter/UserFiles/GenericUser',...
                     'syspath', '/Users/rlhatton/GeometricSystemPlotter/UserFiles/GenericUser/Systems',...
                     'current_system2', {{'three_link_lowRe','three_link_lowRe','serpenoid_lowRe'}},...
                     'current_shch2', {{'circle_1p0','opt_f042eeb5f2c4964883ae8f1aa0982567','circle_6'}});
                 
info_needed.Movies = struct('system', 1,...
           'CCFx', 0,...
           'CCFy', 0,...
       'CCFtheta', 0,...
        'vfieldx', 0,...
        'vfieldy', 0,...
    'vfieldtheta', 0);
    

animate_locomotor_race(0,info_needed)
